---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  Test:
    env:
      TF: ${{ matrix.tf }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf: [M1, M2, M5, M15, M30, H1, H8, D1, W1, MN1]
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: make clean
